ClassDemo/Controllers/ItemCategoryController.cs
using ERP.Project.Data.Context;
using ERP.Project.Data.Models;
using ClassDemo.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClassDemo.Controllers
{
    //[Authorize(Roles ="Admin")]
    [IsAdmin]
    public class ItemCategoryController : BaseController
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemCategoryView()
        {           
            using (var _dbContext = new ProjectManagementDbContext())
            {
                ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
                var itms = _dbContext.ItemCategories.ToList();
                return View(itms);
            }
        }
        [HttpPost]
        public ActionResult ItemCategoryView(ItemCategory cat )
        {
            if (ModelState.IsValid)
            {
                ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
                db.ItemCategories.Add(cat);
                db.SaveChanges();
                return RedirectToAction("ItemCategoryView");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            ItemCategory cat = db.ItemCategories.Find(id);
            db.ItemCategories.Remove(cat);
            db.SaveChanges();
            return RedirectToAction("ItemCategoryView");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            ItemCategory cat = db.ItemCategories.Find(id);
            return View(cat);
        }
        [HttpPost]
        public ActionResult Edit(ItemCategory cat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ItemCategoryView");
            }
            return View(cat);
        }

    }
}

ClassDemo/Controllers/ItemStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassDemo.Models;
using ERP.Project.Data.Context;
using ERP.Project.Data.Models;
using System.Data.Entity;

namespace ClassDemo.Controllers
{
    [IsAdmin]
    public class ItemStatusController : BaseController
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemStatusView()
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            ItemStatus stat = new ItemStatus();
            return View(db.ItemStatuses.ToList());
        }
        [HttpPost]
        public ActionResult ItemStatusView(ItemStatus stat)
        {
            if(ModelState.IsValid)
            {
                ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
                db.ItemStatuses.Add(stat);
                db.SaveChanges();
                return RedirectToAction("ItemStatusView");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            ItemStatus stat = db.ItemStatuses.Find(id);
            db.ItemStatuses.Remove(stat);
            db.SaveChanges();
            return RedirectToAction("ItemStatusView");
        }
        public ActionResult Edit(int id)
        {
            ItemStatus stat = db.ItemStatuses.Find(id);
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            return View(stat);
        }
        [HttpPost]
        public ActionResult Edit(ItemStatus stat)
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            db.Entry(stat).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ItemStatusView");
        }
    }
}

ClassDemo/Controllers/ItemTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERP.Project.Data.Context;
using ERP.Project.Data.Models;
using ClassDemo.Models;
using System.Data.Entity;

namespace ClassDemo.Controllers
{
    [IsAdmin]
    public class ItemTypeController : BaseController
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemTypeView()
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            ItemType it = new ItemType();
            return View(db.ItemTypes.ToList());
        }
        [HttpPost]
        public ActionResult ItemTypeView(ItemType it)
        {
            if(ModelState.IsValid)
            {
                ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
                db.ItemTypes.Add(it);
                db.SaveChanges();
                return RedirectToAction("ItemTypeView");
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            ItemType it = db.ItemTypes.Find(id);
            db.ItemTypes.Remove(it);
            db.SaveChanges();
            return RedirectToAction("ItemTypeView");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            ItemType it = db.ItemTypes.Find(id);
            return View(it);
        }
        [HttpPost]
        public ActionResult Edit(ItemType it)
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            db.Entry(it).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ItemTypeView");
        }
    }
}

ClassDemo/Controllers/MemberController.cs
using ERP.Project.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERP.Project.Data.Context;
using System.Data.Entity;
using static ClassDemo.Controllers.BaseController;

namespace ClassDemo.Controllers
{
    [IsAdmin]
    public class MemberController : BaseController
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();

        public ActionResult AddMember()
        {
            ViewBag.Role = new SelectList(db.Roles, "RoleId", "UserRole");
            Member reg = new Member();
            return View();
        }
        [HttpPost]
        public ActionResult AddMember(Member reg)
        {
            int user = db.Members.Where(m => m.UserName == reg.UserName).Count();
            int email = db.Members.Where(m => m.EmailId == reg.EmailId).Count();
            int userAd = db.Logins.Where(m => m.username == reg.UserName).Count();
            ViewBag.Role = new SelectList(db.Roles, "RoleId", "UserRole");
            if (ModelState.IsValid)
            {
                if (user == 0 && email == 0 && userAd == 0)
                {
                    db.Members.Add(reg);
                    db.SaveChanges();
                    ViewBag.RegStatus = "Registerd Sucessfully";
                    return View();
                }
                if (user >= 1 || userAd >= 1)
                {
                    ViewBag.status = "username already exists";
                }
                if (email >= 1)
                {
                    ViewBag.status = "email Id already exists";
                }
            }
            return View();
        }
        public void checkuser(string username)
        {
            var users = username;

            if (db.Members.Any(m => m.UserName == users) || db.Members.Any(m => m.EmailId == users))
            {
                ViewBag.status = "username already exists";
            }
            int email = db.Members.Where(m => m.EmailId == users).Count();
            if(db.Logins.Any(m => m.username == users))
            {
                ViewBag.status = "email Id already exists";
            }
        }

        public ActionResult Details()
        {
            var id = Session["UserId"];
            ViewBag.Role = new SelectList(db.Roles, "RoleId", "UserRole");
            var det = db.Members.Find(id);
            return View(det);
        }
        [HttpPost]
        public ActionResult Details(Member det)
        {
            ViewBag.Role = new SelectList(db.Roles, "RoleId", "UserRole");
            db.Entry(det).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Members()
        {

            return View(db.Members.Include(m => m.Role).ToList());
        }
        public ActionResult AdminDetails()
        {
            var id = Session["UserId"];
            var det = db.Logins.Find(id);
            return View(det);
        }
        [HttpPost]
        public ActionResult AdminDetails(Member det)
        {
            if (ModelState.IsValid)
            {
                db.Entry(det).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public ActionResult Delete(int Id)
        {
            Member reg = db.Members.Find(Id);
            db.Members.Remove(reg);
            db.SaveChanges();
            return RedirectToAction("Members");
        }
        public ActionResult Edit(int Id)
        {
            ViewBag.Role = new SelectList(db.Roles, "RoleId", "UserRole");
            var det = db.Members.Find(Id);
            return View(det);
        }
        [HttpPost]
        public ActionResult Edit(Member det)
        {
            ViewBag.Role = new SelectList(db.Roles, "RoleId", "UserRole");
            db.Entry(det).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Members");
        }
    }
}

ClassDemo/Views/Shared/_EmpLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <script src="~/Scripts/validation.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Home/Index">SCRUM FRAME</a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                    <li>@Html.ActionLink("View Items", "ItemsList", "Home")</li>
                </ul>
                <ul class="nav navbar-nav" style="float:right;">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Welcome @Session["UserName"].ToString()<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("My Profile", "Details", "Member")</li>
                            <li>@Html.ActionLink("Log Out", "LogOut", "Login")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - COETL</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ClassDemo/Views/Shared/_Layout.cshtml
@using ClassDemo.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <script src="~/Scripts/validation.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="../Home/Index">SCRUM FRAME</a>
              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Items <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Create Item", "CreateItem", "Home")</li>
                            <li>@Html.ActionLink("View Items ", "ItemsList", "Home")</li>
                            <li>@Html.ActionLink("Add by Exel","Excel","Excel")</li>
                        </ul>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Masters<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Item Categories", "ItemCategoryView", "ItemCategory")</li>
                            <li>@Html.ActionLink("Item Priority", "ItemPriorityView", "ItemPriority")</li>
                            <li>@Html.ActionLink("Item Type", "ItemTypeView", "ItemType")</li>
                            <li>@Html.ActionLink("Item Status", "ItemStatusView", "ItemStatus")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Project", "ProjectView", "Project")</li>
                            <li>@Html.ActionLink("Role", "RoleView", "Role")</li>
                        </ul>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Members <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("New Member", "AddMember", "Member")</li>
                            <li>@Html.ActionLink("Members", "Members", "Member")</li>
                            <li>@Html.ActionLink("Members Group", "Index", "Home")</li>
                        </ul>
</ul>
                <ul class="nav navbar-nav" style="float:right;">
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">welcome @Session["UserName"].ToString()<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("My Profile", "AdminDetails", "Member")</li>
                            <li>@Html.ActionLink("Log Out", "LogOut", "Login")</li>
                        </ul>
                    </li>               
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - COETL</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

ClassDemo/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="~/Scripts/validation.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Home/Index">SCRUM FRAME</a>
              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                    <ul  class="nav navbar-nav" style="float:right;">
                        <li>@Html.ActionLink("Login", "Login", "Login")</li>
                    </ul>
                </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - COETL</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>