ClassDemo/Controllers/ItemPriorityController.cs
using ERP.Project.Data.Context;
using ERP.Project.Data.Models;
using ClassDemo.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClassDemo.Controllers
{
    [IsAdmin]
    public class ItemPriorityController : BaseController
    {
        ProjectManagementDbContext db = new ProjectManagementDbContext();
        public ActionResult ItemPriorityView()
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            ItemPriority prio = new ItemPriority();
            return View(db.ItemPriorities.ToList());
        }
        [HttpPost]
        public ActionResult ItemPriorityView(ItemPriority prio)
        {
            if (ModelState.IsValid)
            {
                ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
                db.ItemPriorities.Add(prio);
                db.SaveChanges();
                return RedirectToAction("ItemPriorityView");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
            ItemPriority prio = db.ItemPriorities.Find(id);
            return View(prio);
        }
        [HttpPost]
        public ActionResult Edit(ItemPriority prio)
        {
            if (ModelState.IsValid)
            {
                ViewBag.ColorCode = new SelectList(Colors.GetColors(), "Value", "Text");
                db.Entry(prio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ItemPriorityView");
            }
            return View(prio);
        }
        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                ItemPriority pri = db.ItemPriorities.Find(id);
                db.ItemPriorities.Remove(pri);
                db.SaveChanges();
                return RedirectToAction("ItemPriorityView");
            }
            return View();
        }
    }
}

ClassDemo/Views/ItemPriority/Edit.cshtml
@model ERP.Project.Data.Models.ItemPriority
@using ERP.Project.Data.Models;

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div>
    @using (Html.BeginForm("Edit", "ItemPriority"))
    {
        <table>
            <tr>
                <td>Item Priority Id</td>
                <td>@Html.TextBoxFor(m => m.PriorityId, new { @class = "form-control", @readonly = "null" })</td>
                
            </tr>
            <tr>
                <td>Color Code</td>
                <td>@Html.DropDownList("ColorCode", (IEnumerable<SelectListItem>)ViewBag.ColorCode, "--Color Code-- ", new { @class = "form-control" })</td>
            </tr>
            <tr>
                <td>Item Priority Name</td>
                <td>@Html.TextBoxFor(m=>m.PriorityName,new { @class = "form-control" })</td>
            </tr>
        </table>
        <input class="btn btn-success" type="submit" value="Update" />
    }
</div>

ClassDemo/Views/ItemPriority/ItemPriorityView.cshtml
@model IEnumerable<ERP.Project.Data.Models.ItemPriority>
@using ERP.Project.Data.Models;

@{
    ViewBag.Title = "ItemPriorityView";
}

<h2>Item Priority</h2>

<div>
    @using (Html.BeginForm("ItemPriorityView", "ItemPriority"))
    {
        <table>
            <tr>
                <td>Item Priority Name &nbsp;</td>
                <td>@Html.TextBox("PriorityName", null, new { @class = "form-control" })</td>
                <td>@Html.DropDownList("ColorCode", (IEnumerable<SelectListItem>)ViewBag.ColorCode, "--Color Code-- ", new { @class = "form-control" })</td>
                <td><input class="btn btn-success" type="submit" value="Add" /></td>
            </tr>
        </table>
       
    }
</div>
<br />
<div style="width:400px;">
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Item Priority </th>
                    <th>Actions</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.PriorityId)</td>
                    <td style="background-color:@Html.DisplayFor(modelItem => item.ColorCode)">@Html.DisplayFor(modelItem => item.PriorityName)</td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.PriorityId }) |
                        @Html.ActionLink("Edit", "Edit", new { id = item.PriorityId })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>